# Generated by Django 2.0.6 on 2018-06-02 13:12

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldictionary',
            name='shrtzy',
            field=models.URLField(default=api.models.generate_shrtzy, unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
